[package]
name = "rssl-lexer"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
rssl-text = { path = "../text" }
rssl-tok = { path = "../tok" }
rssl-preprocess = { path = "../preprocess" }
nom = "7.1.1"
