[package]
name = "rssl-typer"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
rssl-text = { path = "../text" }
rssl-ast = { path = "../ast" }
rssl-ir = { path = "../ir" }
rssl-parser = { path = "../parser" }

[dev-dependencies]
rssl-preprocess = { path = "../preprocess" }
